# Generated by Django 5.1.6 on 2025-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='searched_on',
            new_name='search_time',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
