# Generated by Django 5.1.6 on 2025-06-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_searched_on_searchhistory_search_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
