# Generated by Django 5.1.6 on 2025-06-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_searchhistory_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='LinguisticFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linguistic_features', to='dictionary.word')),
            ],
        ),
    ]
